### ISSUE TITLE
I-vectors as input features

### ISSUE THREAD

**Issue by chernzheng** [tzyll/goparrot#1]
I noticed that you did not use i-vectors as input features in your model, but other implementations
used it. For example, [https://github.com/kaldi-asr/kaldi/blob/master/egs/gop/s5/run.sh]. I am wondering if i-vector necessary for computing GOP?

**Comment by tzyll** [comment]
i-vector is not necessary for GOP. Kaldi uses i-vector to improve AM performance (often limited).
